[package]
name = "directip-client"
version = "0.1.0"
authors = ["Guilherme Castel√£o <guilherme@castelao.net>", "Luiz Irber <luiz.irber@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2", features=["cargo"] }
directip = { path = "../" }
log = "0.4"
